[package]
name = "meminfo"
version = "0.1.0"
authors = ["jyuch <jyuch@users.noreply.github.com>"]
edition = "2021"

[dependencies.windows]
version = "0.44"
features = [
    "Win32_System_SystemInformation",
    "Win32_Foundation"
]
