[workspace]

resolver = "2"

members = [
    "compat",
    "cpp-interop",
    "enum-printer",
    "meminfo",
    "print-via-gdi",
    "show-message-box",
    "icon-and-property",
]

[workspace.dependencies]
windows = "0.52"
bindgen = "0.68"
cc = "1.0"
winres = "0.1"
