[package]
name = "cpp-interop"
version = "0.1.0"
authors = ["jyuch <jyuch@users.noreply.github.com>"]
edition = "2018"

[dependencies]

[build-dependencies]
bindgen = { workspace = true }
cc = { workspace = true }
