[package]
name = "show-message-box"
version = "0.1.0"
authors = ["jyuch <jyuch@users.noreply.github.com>"]
edition = "2021"

[dependencies]
winapi = { version = "0.3", features = [ "impl-default", "winuser", ] }
