[package]
name = "print-via-gdi"
version = "0.1.0"
authors = ["jyuch <jyuch@users.noreply.github.com>"]
edition = "2021"

[dependencies]
libc = "0.2"
winapi = { version = "0.3", features = ["std", "impl-default", "minwindef", "windef", "winuser", "winspool", "wingdi", ] }
